package remnant;

public enum TokenType {
	LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_BRACE, RIGHT_BRACE, COMMA, DOT, SEMICOLON,
	PLUS, MINUS, STAR, SLASH, BITWISE_AND, BITWISE_OR,
	
	NOT, NOT_EQUAL,
	EQUAL, EQUAL_EQUAL,
	GREATER, GREATER_EQUAL,
	LESS, LESS_EQUAL,
	LOGICAL_AND, LOGICAL_OR, 
	
	IDENTIFIER, STRING, NUMBER,
	
	IF, ELSE, WHILE, FOR, RETURN, TRUE, FALSE, OUTPUT, SUPER, THIS,
	NULL, CLASS, VAR, FUNCTION,
	
	EOF
}